"""Generate V7__pvr_catalog_data.sql from docs/data/pvr_properties.csv.

Property names/cities come from public listings (see the CSV source column).
Screen counts are used when a source stated them; everything else -- missing
screen counts, seats per screen (200-500), 2/3-class splits, prices and the
movie slate -- is synthetic and seeded by stable keys, so reruns are identical.

Usage: py scripts/generate_pvr_catalog.py
"""
import csv
import pathlib
import random
import uuid

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "data" / "pvr_properties.csv"
TARGET = ROOT / "src" / "main" / "resources" / "db" / "migration" / "V7__pvr_catalog_data.sql"
NAMESPACE = uuid.UUID("6f1d4f7e-3c1b-5b8e-9a51-2f0c8b7d4e10")
ZONE = "Asia/Kolkata"

TIER1 = {"Delhi", "Gurugram", "Noida", "Greater Noida", "Ghaziabad", "Faridabad", "Mumbai",
         "Thane", "Navi Mumbai", "Bengaluru", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad"}
TIER2 = {"Jaipur", "Lucknow", "Chandigarh", "Mohali", "Zirakpur", "Panchkula", "Indore", "Kochi",
         "Nagpur", "Surat", "Vadodara", "Bhopal", "Coimbatore", "Visakhapatnam", "Bhubaneswar",
         "Ludhiana", "Kanpur", "Patna", "Guwahati", "Mysuru", "Mangaluru", "Goa", "Panaji",
         "Nashik", "Rajkot", "Raipur", "Dehradun", "Amritsar", "Vijayawada", "Thiruvananthapuram",
         "Madurai", "Ranchi", "Jammu", "Kalyan", "Mira Road", "Vasai", "Kolhapur", "Aurangabad"}
# Paise per seat by price tier and class.
PRICES = {1: {"A": 55000, "B": 35000, "C": 22000},
          2: {"A": 42000, "B": 28000, "C": 18000},
          3: {"A": 32000, "B": 22000, "C": 15000}}
# Synthetic now-showing slate: (title, language, minutes, weight, blockbuster).
SLATE = [
    ("Sindoor Ki Saugandh", "Hindi", 168, 15, True),
    ("Kaal Chakra: Rise of Asura", "Telugu", 175, 13, True),
    ("Orbit Breakers", "English", 142, 12, True),
    ("Dilli Diaries", "Hindi", 128, 5, False),
    ("Monsoon Wedding Planner", "Hindi", 136, 4, False),
    ("Thalaivan Returns", "Tamil", 162, 6, False),
    ("Kadal Kaatru", "Malayalam", 131, 3, False),
    ("Bengaluru Boys", "Kannada", 139, 3, False),
    ("Shonar Kella Rahasya", "Bengali", 124, 2, False),
    ("Ghar Wapsi Express", "Hindi", 118, 4, False),
    ("Last Light Protocol", "English", 151, 5, False),
    ("The Velvet Heist", "English", 127, 4, False),
    ("Junglee Jugaad", "Hindi", 114, 3, False),
    ("Marathi Manus", "Marathi", 133, 2, False),
    ("Pind Da Sher", "Punjabi", 129, 3, False),
    ("Little Dragon Rescue", "English", 98, 4, False),
    ("Raat Ke Raaz", "Hindi", 121, 3, False),
    ("Varisu Veeran", "Tamil", 156, 4, False),
    ("Hyderabad Heist Club", "Telugu", 144, 3, False),
    ("Cricket Ka Keeda", "Hindi", 137, 3, False),
]


def uid(*parts):
    return str(uuid.uuid5(NAMESPACE, "/".join(parts)))


def sql(text):
    return "'" + text.replace("'", "''") + "'"


def tier(city):
    return 1 if city in TIER1 else 2 if city in TIER2 else 3


def brand(name):
    lowered = name.lower()
    return "INOX" if "inox" in lowered and not lowered.startswith("pvr") else "PVR"


def screen_count(row, rng, price_tier):
    stated = (row.get("screens") or "").strip()
    if stated.isdigit():
        return max(5, min(int(stated), 100))
    low, high = {1: (5, 9), 2: (5, 7), 3: (5, 6)}[price_tier]
    return rng.randint(low, high)


def layout(rng):
    seats = rng.randrange(200, 501, 10)
    if rng.random() < 0.45:
        a = rng.randint(15, 30)
        return seats, {"A": a, "B": 100 - a}
    a, b = rng.randint(8, 15), rng.randint(25, 35)
    return seats, {"A": a, "B": b, "C": 100 - a - b}


def category_seats(seats, split):
    # Mirrors MovieCatalog.createMultiplex: floor shares, last class takes the remainder.
    keys = sorted(split)
    counts, allocated = {}, 0
    for index, key in enumerate(keys):
        count = seats - allocated if index == len(keys) - 1 else seats * split[key] // 100
        counts[key] = count
        allocated += count
    return counts


def main():
    with SOURCE.open(encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    seen, sites = set(), []
    for row in rows:
        name, city, state = row["name"].strip(), row["city"].strip(), row["state"].strip()
        key = (name.lower(), city.lower())
        if not name or not city or key in seen:
            continue
        seen.add(key)
        sites.append((name, city, state, row))
    sites.sort(key=lambda s: (s[1], s[0]))

    out = ["-- Generated by scripts/generate_pvr_catalog.py from docs/data/pvr_properties.csv.",
           "-- Real property names/cities; screen layouts, prices and movie slate are synthetic.",
           ""]
    for tier_key, prices in PRICES.items():
        for category, price in prices.items():
            out.append(f"INSERT INTO movie_catalog_prices VALUES ({tier_key},{sql(category)},{price});")
    for title, language, minutes, weight, blockbuster in SLATE:
        movie = uid("movie", title)
        out.append(f"INSERT INTO movies VALUES ({sql(movie)},{sql(title)},{sql(language)},{minutes});")
        out.append(f"INSERT INTO movie_now_showing VALUES ({sql(movie)},{weight},{str(blockbuster).lower()});")

    screens_total = seats_total = 0
    for name, city, state, row in sites:
        rng = random.Random(f"{name}|{city}")
        price_tier = tier(city)
        count = screen_count(row, rng, price_tier)
        multiplex = uid("multiplex", name, city)
        out.append(f"INSERT INTO movie_multiplexes VALUES ({sql(multiplex)},{sql(name)},{sql(ZONE)},{count});")
        out.append(f"INSERT INTO movie_catalog_sites VALUES ({sql(multiplex)},{sql(brand(name))},"
                   f"{sql(city)},{sql(state)},{price_tier});")
        for number in range(1, count + 1):
            seats, split = layout(rng)
            screen = uid("screen", name, city, str(number))
            out.append(f"INSERT INTO movie_screens VALUES ({sql(screen)},{sql(multiplex)},'Screen {number}',{seats});")
            for category, seat_count in category_seats(seats, split).items():
                out.append(f"INSERT INTO movie_screen_categories VALUES ({sql(screen)},{sql(category)},"
                           f"{split[category]},{seat_count});")
            screens_total += 1
            seats_total += seats
    TARGET.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print(f"multiplexes={len(sites)} cities={len({s[1] for s in sites})} screens={screens_total} seats={seats_total}")


if __name__ == "__main__":
    main()
